version: '3'

services:

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  web_server1:
    image: nginx
    container_name: slave1
    volumes:
      - ./html:/var/www/html
      - ./nginx_conf_backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - php

  web_server2:
    image: nginx
    container_name: slave2
    volumes:
      - ./html:/var/www/html
      - ./nginx_conf_backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - php

  load_balancer:
    image: nginx
    container_name: master
    ports:
      - "80:80"
      - "443:443"
    volumes:
    # - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs_nginx/fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ./certs_nginx/privkey.pem:/etc/letsencrypt/privkey.pem
    networks:
      - frontend
      - backend
   
    depends_on:
      - web_server1
      - web_server2



networks:
  backend:
  frontend:

